name: Check NX30Pro

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            clang \
            flex \
            bison \
            g++ \
            gawk \
            gettext \
            git \
            libncurses-dev \
            libssl-dev \
            python3 \
            rsync \
            unzip \
            zlib1g-dev \
            file \
            wget \
            curl

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load config
        run: |
          cp files/.config .config
          make defconfig

      - name: Check configuration
        run: |
          echo "=============================="
          echo "TARGET CONFIG"
          echo "=============================="
          grep "^CONFIG_TARGET" .config

          echo
          echo "=============================="
          echo "NX30 Device"
          echo "=============================="
          grep -A30 "define Device/h3c_magic-nx30-pro" target/linux/mediatek/image/filogic.mk || true

          echo
          echo "=============================="
          echo "OpenWrt One Device"
          echo "=============================="
          grep -A30 "define Device/openwrt_one" target/linux/mediatek/image/filogic.mk || true

          echo
          echo "=============================="
          echo "Search h3c_magic-nx30-pro"
          echo "=============================="
          grep -R "h3c_magic-nx30-pro" target/linux/mediatek || true

          echo
          echo "=============================="
          echo "Search openwrt_one"
          echo "=============================="
          grep -R "openwrt_one" target/linux/mediatek || true

          echo
          echo "=============================="
          echo "Device List"
          echo "=============================="
          grep "TARGET_DEVICES +=" target/linux/mediatek/image/*.mk || true
